# -*- coding: utf-8 -*-
"""TP5_Simulacion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xYr4DVnS3AyzYNA9KzdFMq6RcY_G0GWb

#Simulacion
"""

pip install fitter

from fitter import Fitter
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

from IPython.display import clear_output

def menorTPS(tpss):
  return np.argmin(tpss)

def medico(tpss, mAnterior, hv):

    p=mAnterior+1

    for i in range(len(tpss)):
        pos = (p + i)

        if pos >= len(tpss):
            pos = pos - len(tpss)

        if tpss[pos] == hv:
            return pos

def iaLunes():
  return stats.recipinvgauss.rvs(
  2.4561342922592946,
  loc=-0.0078118652003398075,
  scale=0.14046317324786345
)

def iaSemana():
    return stats.beta.rvs(
        0.781890038512159,
        53.86125588112104,
        loc=-3.549313219308298e-29,
        scale=16.419629636259508
    )

def iaFinSemana():
    return stats.lomax.rvs(
        5.516660019948807,
        loc=-6.021711805073675e-11,
        scale=1.9569212786728503
    )

stats.recipinvgauss.shapes

def ta():
    return stats.f.rvs(
        dfn=1.8565442689118927,
        dfd=38.61216990606688,
        loc=1.0166666666666666,
        scale=4.023906662604354
    )

def ia(n):
  match n:
    case 0:
      return iaLunes()
    case 1:
      return iaSemana()
    case 2:
      return iaFinSemana()

def arrepentido(nss):
  if nss>=150:
    return True
  else:
    return False

2#Valores iniciales y variables
n = int(input("Ingrese numero de medicos: "))
#tf = int(input("Ingrese largo de la simulacion en minutos: "))
tf=172000
periodo = int(input("Ingrese 0 para lunes, 1 para semana, 2 para fin de semana :"))
hv=tf*300
ns=0
tps=[hv]*n
t=0
tpll=0

sts=0
stll=0
sta=0
nt=0
sto=[0]*n
ito=[0]*n
imc=0
pto=[0]*n
arr=0


while t<tf or ns>0:

  itps = menorTPS(tps)
  if tpll<tps[itps]:
    t=tpll
    #print(t,"e")
    intervalo=ia(periodo)
    tpll=t+intervalo
    if not arrepentido(ns):
      stll=stll+t
      nt=nt+1
      ns=ns+1
      if ns<=n:
        imc=medico(tps,imc,hv)
        atencion=ta()
        print("ta ", atencion," e ",imc)
        tps[imc]=t+atencion
        sto[imc]=sto[imc]+t-ito[imc]
        sta=sta+atencion
    else:
      arr=arr+1
  else:
    t=tps[itps]
    print(t," s ", itps)
    ns=ns-1
    sts=sts+t
    if ns>=n:
      atencion=ta()
      print("ta s ", atencion)
      tps[itps]=t+atencion
      sta=sta+atencion
    else:
      tps[itps]=hv
      ito[itps]=t

  if t>=tf:
    tpll=hv




clear_output(wait=True)

#Calculos de variables resultado
pec=(sts-stll-sta)/nt
pps=(sts-stll)/nt
for i in range(n):
  pto[i]=sto[i]/t


#for i in range(n):
#  print("Porcentaje de tiempo oscioso medico numero ", i , " :",pto[i]*100)
print("Cantidad de medicos: ", n)
print("Tiempo de ejecucion: ", t/60," horas. Tiempo establecido :", tf/60)
print("Promedio de espera en cola: ",pec)
print("Promedio de permanencia en el sistema: ",pps)
print("Promedio de porcentaje de tiempo oscioso :", np.mean(pto)*100)
print("Porcentaje de arrepentidos :",(arr/(nt+arr))*100)

#print("nt ", nt,"sts ",sts,"stll ",stll,"sta ",sta)